[project]
name = "elwis-api"
version = "1.4.2"
description = ""
readme = "README.md"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "psycopg2-binary>=2.9.10",
    "pydantic>=2.11.7",
    "sqlmodel>=0.0.24",
    "zeep>=4.3.1",
]

[tool.setuptools]
packages = ["app", "api_client"]


